# Generated by Django 4.1.4 on 2022-12-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('product_description', models.TextField(max_length=200)),
                ('product_specifications', models.TextField(max_length=512)),
                ('product_care', models.TextField(max_length=512)),
                ('product_thumbnail', models.ImageField(blank=True, null=True, upload_to='product_thumbnails')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sale_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('in_stock', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Waiting', 'Waiting')], max_length=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.subsubcategory')),
                ('product_images', models.ManyToManyField(blank=True, related_name='images', to='products.picture')),
            ],
        ),
    ]
