# Generated by Django 4.1.4 on 2022-12-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
