# Generated by Django 4.1.4 on 2022-12-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Waiting', 'Waiting')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
