# Generated by Django 4.1.4 on 2022-12-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_main_description',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=200),
        ),
    ]
