# Generated by Django 4.1.4 on 2022-12-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_product_main_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_main_description',
            new_name='product_specifications',
        ),
    ]
