# Generated by Django 4.1.4 on 2022-12-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_id_alter_subcategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
